In [1]:
import numpy as np
a = np.array([[1,2,1,4],
              [5,6,7,8],
              [7,4,3,2]])
print(np.shape(a))
b = np.shape(a)[1]
# b = np.shape(a)
print(b)

(3, 4)
4


In [5]:
import csv

f1 = open('word.csv', 'r', encoding="ISO-8859-1")
rdr1 = csv.reader(f1)
word = []
for row in rdr1:
    word.append(row)
f1.close()
word = np.asarray(word)

In [10]:
dataword = word
print(a[1])
print(np.where(a[0]==1))
print(np.where(a[0]==1)[0])
idxword = np.where(a[0]==1)[0]
print(np.shape(dataword))
print(dataword[idxword])
print(len(idxword))
print(np.square(a))

[5 6 7 8]
(array([0, 2]),)
[0 2]
(28624, 1)
[['holes']
 ['top_secret']]
2
[[ 1  4  1 16]
 [25 36 49 64]
 [49 16  9  4]]
